### ISSUE TITLE
np.linalg.norm处理的目的是什么

### ISSUE THREAD

**Issue by allensky708** [vearch/python-algorithm-plugin#2]
插件的util中：
def normlize(feat):
    feat = feat/np.linalg.norm(feat)
    return feat.tolist()

请问特征向量在这里使用np.linalg.norm的目的是什么？
那么我用插件入库数据，但没有走插件转换向量去查询的时候结构就不对了？

- [ ]

**Comment by gDreamcatcher** [comment]
你好， np.linalg.norm的目的主要是为了使用内积计算替代余弦距离计算，以此来加快检索的速度
