### ISSUE TITLE
使用插件插入图片数据后直接使用特征进行检索，检索失败。

### ISSUE THREAD

**Issue by caolist** [vearch/python-algorithm-plugin#7]
gamma.log 中显示：
ERROR 2021-02-08 07:33:13,760 gamma_engine.cc:322 index not trained!

文档中指出：
Note：If no index is created, you need add a parameter in request to enforce brute force search rather than index search, eg:

curl -H "content-type: application/json" -XPOST -d '{ "query": { "sum": [{"feature":"../images/COCO_val2014_000000123599.jpg", "field":"feature1"}]},"is_brute_search":1}' http://127.0.0.1:4101/test/test/_search

加上这个 is_brute_search 参数，可以成功检索。

想知道 所谓的 train 是什么意思？该如何理解 is_brute_search ？
谢谢！

**Comment by gDreamcatcher** [comment]
`train`是训练索引，`is_brute_search`就是不使用索引，进行暴力搜索

**Comment by caolist** [comment]
> `train` 是训练索引，`is_brute_search` 就是不使用索引，进行暴力搜索

谢谢解答，请问我该如何触发训练索引，从而可以不使用暴力搜索呢？

**Comment by caolist** [comment]
> > `train` 是训练索引，`is_brute_search` 就是不使用索引，进行暴力搜索
> 
> 谢谢解答，请问我该如何触发训练索引，从而可以不使用暴力搜索呢？

已经找到解决方法了。
